### PR TITLE
Fix archive! and unarchive! methods

### PR DESCRIPTION
**Pull request by github0013**

### CODE REVIEW

**Comment by github0013** [comment]
inspired by #195

**Comment by unkrich** [comment]
@github0013 The message_id option doesn't seem to be working for me - can you check this?

**Comment by johnnyshields** [comment]
What's the difference between this PR and #234? Which one should I merge?

**Comment by unkrich** [comment]
#234 has other changes made to it as well. Either one would work as long as
the other changes are good, but I didn't test/take a look at the others in
234.

Thanks,
Kevin

**Comment by github0013** [comment]
@johnnyshields 

#234 should be subjected to merged.   I am personally using it for a while, doing fine.  

I have this much in my gmail, and it's fast enough to archive and unarchive.

#233 is slow because the find method look through all emails. #234 is using `rfc822msgid` instead.
https://support.google.com/mail/answer/7190?hl=en

**Comment by johnnyshields** [comment]
Fixed by https://github.com/gmailgem/gmail/pull/234/files

**Pull request closed without merging**
