### PR TITLE
add imap idle method to wait for new messages

### PR DESCRIPTION
**Pull request by johnnyshields**
PR for gmailgem/gmail#93

### CODE REVIEW

**Comment by johnnyshields** [comment]
(Update Jan 19, 2015) This PR needs to have the line containing `"All Mails"` to be localized before it can be merged.

**Comment by bootstraponline** [comment]
> We can’t automatically merge this pull request.
> Use the command line to resolve conflicts before continuing.

**Comment by jcarbo** [comment]
@bootstraponline I reviewed this and it's definitely WIP. I'm taking a stab at a more robust version of this that I will likely be finishing up this weekend. See #157 for an updated discussion on how we're planning to implement `IDLE`.

**Comment by bootstraponline** [comment]
Should we close this then until it's ready?

**Comment by jcarbo** [comment]
Yea probably makes sense. I'll close it out.

**Pull request closed without merging**
