### PR TITLE
Labels#localize should never return nil

### LINKED ISSUE #175: NoMethodError: undefined method `gsub' for nil:NilClass when accessing non-existent special mailbox
If you disable IMAP access to one of the special mailboxes (e.g. All Mail) from Gmail, and then try to access that mailbox over IMAP, you will get a NoMethodError.

```
> gmail = Gmail.connect! *options
> gmail.mailbox(:all)
NoMethodError: undefined method `gsub' for nil:NilClass
	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/net/imap.rb:970:in `decode_utf7'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/mailbox.rb:23:in `initialize'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/client/base.rb:163:in `new'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/client/base.rb:163:in `block in mailbox'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/client/base.rb:161:in `synchronize'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/client/base.rb:161:in `mailbox'
```

I would probably expect it to behave the same way as it does for any other nonexistent mailbox:

```
> gmail.mailbox('banana face')
Net::IMAP::NoResponseError:  Unknown Mailbox: banana face (Failure)
	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/net/imap.rb:1171:in `get_tagged_response'
	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/net/imap.rb:1225:in `block in send_command'
	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/net/imap.rb:1207:in `send_command'
	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/net/imap.rb:453:in `block in select'
	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /app/vendor/ruby-2.2.1/lib/ruby/2.2.0/net/imap.rb:451:in `select'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/client/base.rb:207:in `switch_to_mailbox'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/client/base.rb:164:in `block in mailbox'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/client/base.rb:161:in `synchronize'
	from /app/vendor/bundle/ruby/2.2.0/gems/gmail-0.5.0/lib/gmail/client/base.rb:161:in `mailbox'
```

I'll post a PR shortly.

### PR DESCRIPTION
**Pull request by afn**
Fixes #175

### CODE REVIEW

**Comment by johnnyshields** [comment]
@gmailgem/owners can someone confirm this please?

**Comment by afn** [comment]
Any update on this?  Thanks!

**Comment by bootstraponline** [comment]
The code looks reasonable and the tests pass. Merged.

**Comment by bootstraponline** [comment]
This has been released in version 0.6.0 of the gmail gem. Thanks for contributing!

**Pull request merged**
