### PR TITLE
Searching by message id

### PR DESCRIPTION
**Pull request by asiniy**
subj. Very helpful for solving issues like these:

https://github.com/gmailgem/gmail/issues/168
https://github.com/gmailgem/gmail/issues/160

### CODE REVIEW

**Comment by paloaltocorp** [comment]
+1

**Comment by johnnyshields** [comment]
@asiniy this PR is failing tests. If you delete the recording for the failing test, you can see that it's because X-GM-MSGID is a very large integer (e.g. 1515289570987380532)--too large for the IMAP protocol to handle.

**Comment by johnnyshields** [comment]
Also, I believe this can replace PR #160. The problem with PR #160 is that it downloads all messages to the Ruby client first, then iterates them on the server side. We should be using your method, which is a server-side search.

**Comment by johnnyshields** [comment]
@asiniy any chance to investigate the failing specs here?

**Comment by asiniy** [comment]
@johnnyshields I finished the contract related to this gem and now I don't have big requirements for this gem. I'll solve the issues w/ specs in the case of free time

**Comment by lcpriest** [comment]
This was partially merged in https://github.com/gmailgem/gmail/pull/242

**Comment by johnnyshields** [comment]
@lcpriest are you able to help rebase this?

**Comment by lcpriest** [comment]
@johnnyshields I can't remember if I could get this working - I ended up using this finder method:
```
      def find(rfc822msgid)
        client.mailbox(:all).find(gm: "rfc822msgid:#{rfc822msgid.to_s.strip}").first
      end
```

**Comment by johnnyshields** [comment]
OK that's what I merged in #234. I will close this PR.

**Pull request closed without merging**
